name: Backend Build Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Azure Cosmos DB Emulator
      uses: southpolesteve/cosmos-emulator-github-action@v1
    - name: Install Dependencies
      run: yarn
    - name: Run the tests 
      run: yarn test
      env:
       COSMOSDB_ENDPOINT: https://localhost:8081
       COSMOSDB_KEY: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
       ENTRYPOINT: https://aka.cscms.me
      
